language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - sudo mv arduino-1.6.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - git clone --branch=master https://github.com/GreyGnome/EnableInterrupt.git /usr/local/share/arduino/libraries/EnableInterrupt
  - git clone --branch=master https://github.com/rocketscream/Low-Power.git /usr/local/share/arduino/libraries/Low-Power
  - git clone --branch=master https://github.com/pa-pa/AskSinPP.git /usr/local/share/arduino/libraries/AskSinPP
  - git clone --branch=master https://github.com/finitespace/BME280.git /usr/local/share/arduino/libraries/BME280
script:
  - arduino --verify --board arduino:avr:uno $PWD/HB-UNI-Sen-WEA.ino
notifications:
  email:
    on_success: change
    on_failure: change
